### ISSUE TITLE
Deprecated interfaces with 8.1

### ISSUE THREAD

**Issue by gerab** [midnite81/alfred-uuid#1]
Throw warnings with PHP 8.1. That affects clipboard result

Deprecated: Ramsey\Uuid\Uuid implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in ~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FB03326B-8E4A-4D96-BCCF-CC369EE54A55/vendor/ramsey/uuid/src/Uuid.php on line 34

Deprecated: Return type of Ramsey\Collection\AbstractArray::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FB03326B-8E4A-4D96-BCCF-CC369EE54A55/vendor/ramsey/collection/src/AbstractArray.php on line 84

Deprecated: Return type of Ramsey\Collection\AbstractArray::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in ~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FB03326B-8E4A-4D96-BCCF-CC369EE54A55/vendor/ramsey/collection/src/AbstractArray.php on line 84

Deprecated: Ramsey\Uuid\Builder\BuilderCollection implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in ~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FB03326B-8E4A-4D96-BCCF-CC369EE54A55/vendor/ramsey/uuid/src/Builder/BuilderCollection.php on line 31

Deprecated: Ramsey\Uuid\Provider\Node\NodeProviderCollection implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in ~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FB03326B-8E4A-4D96-BCCF-CC369EE54A55/vendor/ramsey/uuid/src/Provider/Node/NodeProviderCollection.php on line 25

Deprecated: Ramsey\Uuid\Rfc4122\Fields implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in ~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FB03326B-8E4A-4D96-BCCF-CC369EE54A55/vendor/ramsey/uuid/src/Rfc4122/Fields.php on line 41

Deprecated: Ramsey\Uuid\Rfc4122\UuidV4 implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in ~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FB03326B-8E4A-4D96-BCCF-CC369EE54A55/vendor/ramsey/uuid/src/Rfc4122/UuidV4.php on line 30

Deprecated: Ramsey\Uuid\Type\Hexadecimal implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in ~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FB03326B-8E4A-4D96-BCCF-CC369EE54A55/vendor/ramsey/uuid/src/Type/Hexadecimal.php on line 33

**Comment by midnite81** [comment]
Hi @gerab, just to let you know this now works with php 8.1. I have updated it both on [Alfred's workflow repository](http://www.packal.org/workflow/generate-universally-unique-identifier-v4-uuid) and also on [GitHub](https://github.com/midnite81/alfred-uuid/releases/tag/v1.2.0).
